/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.examples.abelanav2.grpc;

@SuppressWarnings("hiding")
public final class EditPhotoRequest extends
    com.google.protobuf.nano.MessageNano {

  private static volatile EditPhotoRequest[] _emptyArray;
  public static EditPhotoRequest[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new EditPhotoRequest[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional int64 photo_id = 1;
  public long photoId;

  // optional string description = 2;
  public java.lang.String description;

  public EditPhotoRequest() {
    clear();
  }

  public EditPhotoRequest clear() {
    photoId = 0L;
    description = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.photoId != 0L) {
      output.writeInt64(1, this.photoId);
    }
    if (!this.description.equals("")) {
      output.writeString(2, this.description);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.photoId != 0L) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt64Size(1, this.photoId);
    }
    if (!this.description.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.description);
    }
    return size;
  }

  @Override
  public EditPhotoRequest mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.photoId = input.readInt64();
          break;
        }
        case 18: {
          this.description = input.readString();
          break;
        }
      }
    }
  }

  public static EditPhotoRequest parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new EditPhotoRequest(), data);
  }

  public static EditPhotoRequest parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new EditPhotoRequest().mergeFrom(input);
  }
}
