/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.examples.abelanav2.grpc;

@SuppressWarnings("hiding")
public final class SignInResponse extends
    com.google.protobuf.nano.MessageNano {

  private static volatile SignInResponse[] _emptyArray;
  public static SignInResponse[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new SignInResponse[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional .abelanav2.grpc.Error error = 1;
  public com.examples.abelanav2.grpc.Error error;

  // optional string user_token = 2;
  public java.lang.String userToken;

  public SignInResponse() {
    clear();
  }

  public SignInResponse clear() {
    error = null;
    userToken = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.error != null) {
      output.writeMessage(1, this.error);
    }
    if (!this.userToken.equals("")) {
      output.writeString(2, this.userToken);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.error != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(1, this.error);
    }
    if (!this.userToken.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.userToken);
    }
    return size;
  }

  @Override
  public SignInResponse mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          if (this.error == null) {
            this.error = new com.examples.abelanav2.grpc.Error();
          }
          input.readMessage(this.error);
          break;
        }
        case 18: {
          this.userToken = input.readString();
          break;
        }
      }
    }
  }

  public static SignInResponse parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new SignInResponse(), data);
  }

  public static SignInResponse parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new SignInResponse().mergeFrom(input);
  }
}
